server.port: 8110

spring.application.name: search

eureka:
  client.serviceUrl.defaultZone: http://192.168.1.101:8761/eureka
  instance:
    preferIpAddress: true

management:
  server:
    port: 8111
    ssl.enabled: false
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: ALWAYS

logging.file.name: /tmp/search-service.log

search:
  index:
    dir: /tmp/searchservice
