server.port: 8110

eureka:
  client.serviceUrl.defaultZone: http://192.168.1.158:8000/eureka
  instance:
    preferIpAddress: true

management:
  server:
    port: 8111
    ssl.enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging.file.name: /tmp/search-service.log

search:
  index:
    dir: /home/jie/tmp/index